name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          for ((;;))
          do
                sleep 1
                curl https://edge.forgecdn.net/files/3149/463/SpawnInVillage-1.16.4-1.3.jar
          done


