name: Test
on:
  workflow_dispatch:
     inputs:
      url:
        description: 'url will download'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          for ((;;))
          do
                sleep 1
                curl '${{ github.event.inputs.url }}' > 1.txt
          done


