name: YouGet
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'url will download'
        required: true
      name:
        description: 'name will save'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: you-get
      - name: Install Uploader
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -q -O uploader
          chmod 777 ./uploader
      - name: Install You-get
        run: |
          sudo pip3 install you-get
          sudo apt-get install ffmpeg
      - name: Save Token
        run: 'echo "$TOKEN" > auth.json'
        shell: bash
        env:
          TOKEN: ${{secrets.TOKEN}}
      - name: Dwonload File
        run: |
          you-get '${{ github.event.inputs.url }}' -O ${{ github.event.inputs.name }}
      - name: Upload
        run: |
          ./uploader -s ./${{ github.event.inputs.name }} -t 10 -r offline
