name: YouGet
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'url will download'
        required: true
      name:
        description: 'name will save'
        required: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/scoop
          key: you-get-scoop-v1.0
      - name: Install You-get
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install python3
          pip3 install you-get
          scoop install ffmpeg
          scoop install wget
        shell: powershell
      - name: Install Uploader
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/win/OneDriveUploader.exe -O ~/scoop/uploader.exe
        shell: powershell
      - name: Save Token
        run: 'echo "$TOKEN" > auth.json'
        shell: bash
        env:
          TOKEN: ${{secrets.TOKEN}}
      - name: Dwonload File
        run: |
          mkdir '${{ github.event.inputs.name }}'
          you-get '${{ github.event.inputs.url }}' -o './${{ github.event.inputs.name }}'
      - name: Upload
        run: |
          ~/scoop/uploader -s './${{ github.event.inputs.name }}' -t 10 -r offline -b 60
